### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by prologic** [taigrr/colorhash#3]
Once #1 and #2 are done, please cut a release 👌

**Comment by taigrr** [comment]
I can cut a release as a sub-v1 release, but this project is subject to change still. I have more APIs to add and I'm not sure how they will cause the API to change. This will become more clear as two other projects of mine (simplecolor & colortheme) draw to completion

**Comment by prologic** [comment]
A sub-zero release is fine 👌

**Comment by taigrr** [comment]
v0.5.0 released
